Recover cached repos from corrupt object files
When a VM hosting an executor or merger crashes it can leave created
but unwritten object files behind. Those render the cached git repo
useless and the only way to recover currently is to manually delete
the repo. Otherwise all jobs using that repo will end up with the
MERGER_FAILURE result [1]. We can easily catch this error and delete
the cached repo in this case to force a clean clone when retrying.

[1] Trace:
2019-04-26 11:01:29,699 ERROR zuul.Merger: Unable to update org/project
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.7/site-packages/zuul/merger/merger.py", line 598, in updateRepo
    repo.reset()
  File "/opt/zuul/lib/python3.7/site-packages/zuul/merger/merger.py", line 255, in reset
    self.update()
  File "/opt/zuul/lib/python3.7/site-packages/zuul/merger/merger.py", line 432, in update
    self._git_fetch(repo, 'origin', tags=True)
  File "/opt/zuul/lib/python3.7/site-packages/zuul/merger/merger.py", line 216, in _git_fetch
    **kwargs)
  File "/opt/zuul/lib/python3.7/site-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/zuul/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/zuul/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --tags origin
  stderr: 'error: object file .git/objects/b8/b6c200917c5c0c9e7d329d9278645153f2740e is empty
error: object file .git/objects/b8/b6c200917c5c0c9e7d329d9278645153f2740e is empty
fatal: loose object b8b6c200917c5c0c9e7d329d9278645153f2740e (stored in .git/objects/b8/b6c200917c5c0c9e7d329d9278645153f2740e) is corrupt
fatal: The remote end hung up unexpectedly'

Change-Id: I499a89a154c03f3efcb364434d27917cd43739b0