Only report to changes in gerrit
We see frequent exceptions [1] in our zuul while it's trying to report to
branches in gerrit. Since reporting in gerrit is only possible for
changes filter that.

[1] Traceback:
ERROR zuul.Pipeline.tenant.post: Exception while reporting
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.6/site-packages/zuul/manager/__init__.py", line 184, in sendReport
    ret = reporter.report(item)
  File "/opt/zuul/lib/python3.6/site-packages/zuul/driver/gerrit/gerritreporter.py", line 77, in report
    comments, zuul_event_id=item.event)
  File "/opt/zuul/lib/python3.6/site-packages/zuul/driver/gerrit/gerritconnection.py", line 945, in review
    file_comments, zuul_event_id=zuul_event_id)
  File "/opt/zuul/lib/python3.6/site-packages/zuul/driver/gerrit/gerritconnection.py", line 966, in review_ssh
    changeid = '%s,%s' % (change.number, change.patchset)
AttributeError: 'Branch' object has no attribute 'number'

Change-Id: I1f8d3073ea963b411fa2d1c76ba05925525ba537