Update patch set 10
Patch Set 10: Code-Review-1

And we need to keep the python binary in the venv :(  When using a symlink as of patchset 10, python no more lookup modules in the venv site-packages:

 ImportError: No module named zuul.cmd.cloner 

The system path is indeed different and I have confirmed that removing the symlink and copying /usr/bin/python2.7 change the sys.path + solve the issue.

I found an explanation in PEP405 which proposed to integrate virtual env in mainline python (done in python 3.3) https://www.python.org/dev/peps/pep-0405/#copies-versus-symlinks :

 Virtualenv must copy the binary in order to provide
 isolation, as Python dereferences a symlinked executable
 before searching for sys.prefix .

We could monkey patch and inject the path we need in sys.path() but it seems easier to me to restore the binary and the dh-virtualenv trigger to keep the binary up-to-date.

Patch-set: 10
Label: Code-Review=-1