Make test_playbook more robust
The test test_playbook runs a job that should result in a
timeout. Therefore it sets a small timeout. In rare cases however the
timeout already aborts the pre run phase of the job which results in a
retry. In this case the first found result of that job is not
TIMED_OUT but None [1]. To make that more robust add a result filter
to getJobFromHistory which lets us get the build with the TIMED_OUT
result.

[1] Trace:
Traceback (most recent call last):
  File "/home/zuul/src/opendev.org/zuul/zuul/tests/unit/test_v3.py", line 2574, in test_playbook
    self.assertEqual(build_timeout.result, 'TIMED_OUT')
  File "/home/zuul/src/opendev.org/zuul/zuul/.tox/py35/lib/python3.5/site-packages/testtools/testcase.py", line 411, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/zuul/src/opendev.org/zuul/zuul/.tox/py35/lib/python3.5/site-packages/testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: None != 'TIMED_OUT'

Change-Id: I9c33fb9c42d8b31b02a7559666467b0d9407aaa3