wmf: pin python-daemon <2.1.0
Causes Zuul scheduler to fails layout validation with:

daemon.daemon.DaemonOSEnvironmentError: Unable to change process owner
([Errno 1] Operation not permitted)

Bug: T119741
Change-Id: Ia0d3a6f5979183bca76d3553f3e3b3dcf43350f2