Update timeout_handler to check for path first
We recently had a failure in test_clone_timeout test, which looked to
fail because we tried to delete a directory that didn't exist:

Traceback (most recent call last):
  File "/home/zuul/src/opendev.org/zuul/zuul/zuul/merger/merger.py", line 62, in timeout_handler
    yield
  File "/home/zuul/src/opendev.org/zuul/zuul/zuul/merger/merger.py", line 200, in _git_clone
    kill_after_timeout=self.git_timeout)
  File "/home/zuul/src/opendev.org/zuul/zuul/.tox/py36/lib/python3.6/site-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/zuul/src/opendev.org/zuul/zuul/.tox/py36/lib/python3.6/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/zuul/src/opendev.org/zuul/zuul/.tox/py36/lib/python3.6/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('/home/zuul/src/opendev.org/zuul/zuul/tests/fixtures/fake_git.sh') failed due to: exit code(-9)
  cmdline: /home/zuul/src/opendev.org/zuul/zuul/tests/fixtures/fake_git.sh clone /tmp/tmphcu80qlj/zuul-test/upstream/org/project1 /tmp/tmphcu80qlj/zuul-test/workspace
  stdout: 'clone /tmp/tmphcu80qlj/zuul-test/upstream/org/project1 /tmp/tmphcu80qlj/zuul-test/workspace'
  stderr: 'Timeout: the command "/home/zuul/src/opendev.org/zuul/zuul/tests/fixtures/fake_git.sh clone /tmp/tmphcu80qlj/zuul-test/upstream/org/project1 /tmp/tmphcu80qlj/zuul-test/workspace" did not complete in 0 secs.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zuul/src/opendev.org/zuul/zuul/tests/unit/test_merger_repo.py", line 124, in test_clone_timeout
    work_repo._ensure_cloned()
  File "/home/zuul/src/opendev.org/zuul/zuul/zuul/merger/merger.py", line 168, in _ensure_cloned
    self._git_clone(clone_url)
  File "/home/zuul/src/opendev.org/zuul/zuul/zuul/merger/merger.py", line 200, in _git_clone
    kill_after_timeout=self.git_timeout)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/zuul/src/opendev.org/zuul/zuul/zuul/merger/merger.py", line 66, in timeout_handler
    shutil.rmtree(path)
  File "/home/zuul/src/opendev.org/zuul/zuul/.tox/py36/lib/python3.6/shutil.py", line 471, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/zuul/src/opendev.org/zuul/zuul/.tox/py36/lib/python3.6/shutil.py", line 469, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmphcu80qlj/zuul-test/workspace'

Add a check to see if the path we are trying to delete actually exists.

Change-Id: I35a12423dd85c1a5944f694ee7621b8aee7c515a
Signed-off-by: Paul Belanger <pabelanger@redhat.com>