Cap xterm.js to < 3.14
This breaks setting the color theme [1].

[1] Trace:
TypeError: Cannot read property 'setTheme' of undefined
Terminal../node_modules/xterm/lib/Terminal.js.Terminal._setTheme
src/zuul/web/node_modules/xterm/lib/Terminal.js:587

Change-Id: I15041815224dd9e0132202ba3c4aebd50466a8ec