cli: prevent exception for the show command
The cli doesn't have a columns arguments and the show command fail
with:
Traceback (most recent call last):
  File "zuul/cmd/client.py", line 205, in main
    if self.args.func():
  File "zuul/cmd/client.py", line 307, in show_running_jobs
    if self.args.columns.upper() == 'ALL':
AttributeError: 'Namespace' object has no attribute 'columns'

This change removes the columns filtering.

Change-Id: I99f940059882320865429dccd6ab24a670f6d51c