Revert "Tune automatic garbage collection of git repos"
This reverts commit 79e50c04103098632de2ca47b18e08931925963b.

We suspect this is causing this error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zuul/merger/merger.py", line 841, in _mergeChange
    zuul_event_id=zuul_event_id)
  File "/usr/local/lib/python3.5/dist-packages/zuul/merger/merger.py", line 525, in merge
    repo.git.merge(*args)
  File "/usr/local/lib/python3.5/dist-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git merge -s resolve FETCH_HEAD
  stderr: 'fatal: not something we can merge in .git/FETCH_HEAD: 3298c8f88b7b3fd49f35b0342ebb98f052f8358f		'refs/changes/83/723083/2' of ssh://review.opendev.org:29418/vexxhost/openstack-operator'

Change-Id: I2e917710110a3ad85690d1cae53122ada005e4e8