gerrit: disable poller when no http authentication is defined
When a gerrit connection is configured without event_stream
and password or auth_type, then the poller is failing with
`AttributeError: 'NoneType' object has no attribute 'get'`
when doing the initial simpleQueryHTTP.

Change-Id: I74a7408a49091f2dc9c41f657ba68e336ff84c40