Don't reset file list to None in updateChange
Change I9c77b35f0da4d892efc420370c04bcc7070c7676 was supposed to make
the file list of a pull request immutable in order to avoid race
conditions. However it was overlooked that the files list also should
not be reset to None if it's already defined. Otherwise there could be
a race between an event causing the reset to None and job freezing
that checks for None and then relies on the existence [1].

[1] Trace:
 2020-01-16 09:21:09,300 ERROR zuul.Pipeline.check: Error freezing job graph for (...) in check>
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.6/site-packages/zuul/manager/__init__.py", line 893, in prepareItem
    item.freezeJobGraph()
  File "/opt/zuul/lib/python3.6/site-packages/zuul/model.py", line 2240, in freezeJobGraph
    self, ppc, skip_file_matcher)
  File "/opt/zuul/lib/python3.6/site-packages/zuul/model.py", line 4274, in createJobGraph
    self._createJobGraph(item, ppc, ret, skip_file_matcher)
  File "/opt/zuul/lib/python3.6/site-packages/zuul/model.py", line 4229, in _createJobGraph
    not frozen_job.changeMatchesFiles(change):
  File "/opt/zuul/lib/python3.6/site-packages/zuul/model.py", line 1690, in changeMatchesFiles
    if self.file_matcher and not self.file_matcher.matches(change):
  File "/opt/zuul/lib/python3.6/site-packages/zuul/change_matcher.py", line 155, in matches
    if matcher.matches(change):
  File "/opt/zuul/lib/python3.6/site-packages/zuul/change_matcher.py", line 91, in matches
    for file_ in change.files:
TypeError: 'NoneType' object is not iterable

Change-Id: Ia1f1f606ffe181f34ced9533c854004a98a9681a