wmf: change number must be a string when formatting
Gerrit 2.14 changed its json formatting of changes. The change and
patchset numbers are now numbers instead of string.

When trying to get the base path of a change, Zuul reconstructs the
change reference path based on the change number:

 change_number[-2:]

Since change_number is now an int, that causes an exception:
    TypeError: 'int' object has no attribute '__getitem__'

Another such case got fixed upstream and is already cherry picked:
https://review.openstack.org/#/c/433748/  But that did not address all
concerns.

Hack ChangeIsh.getBasePath() to cast the change number to a string.

I have run the test without the patch and it fails exactly like in
production.  Applying the patch fix the test.

Bug: T186381
Change-Id: Id2dfc93979a63dd4f4c3d34da6b4927df058e3da