Start ignoring certain Gerrit events
Since starting our deployment to GerritHub, we noticed that we have
a bunch of tracebacks due to their usage of the 'evict-cache' plugin
which fires events that Zuul fails to handle.

  2020-01-29 09:36:04,878 WARNING zuul.GerritEventConnector: [e: 7e8d5af82abf4670a67833ef28599711] Received unrecognized event type 'cache-eviction' from Gerrit. Can not get account information.
  2020-01-29 09:36:04,879 ERROR zuul.GerritEventConnector: Exception moving Gerrit event:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/zuul/driver/gerrit/gerritconnection.py", line 269, in run
      self._handleEvent()
    File "/usr/local/lib/python3.7/site-packages/zuul/driver/gerrit/gerritconnection.py", line 229, in _handleEvent
      self.connection.logEvent(event)
    File "/usr/local/lib/python3.7/site-packages/zuul/connection/__init__.py", line 50, in logEvent
      event=event))
    File "/usr/local/lib/python3.7/site-packages/zuul/driver/gerrit/gerritmodel.py", line 164, in __repr__
      self.canonical_project_name)
    File "/usr/local/lib/python3.7/site-packages/zuul/model.py", line 3252, in canonical_project_name
      return self.project_hostname + '/' + self.project_name
  TypeError: can only concatenate str (not "NoneType") to str

This patch introduces some basic infrastructure to be able to ignore
certain events from Gerrit to avoid the unrecognized event error and
the traceback.  While this could become a "whack-a-mole" over time,
given the various different Gerrit's we are connected to, there seems
to be very little usage of events in plugins so it might be very little.

It also covers the case for one of the more popular deployments which
improves user experience overall.

Change-Id: Icddcc2a54b0d5c9a65c387d7df31fc060eeeb13a