Fix 0018-wmf-ignore-submit-error-on-merged-change
The patch to ignore submit errors when a change is already merged was
wrong. When a change is already merged, the _ssh() call would raise an
exception and has no return value. Thus the previous patch doing:

  if err and 'change is merged' in err

Caused:

  UnboundLocalError: local variable 'err' referenced before assignment

Instead, attach the stderr to the exception and inspect that.

Reference: T203846#5492011

Bug: T203846
Change-Id: I83d84c35be1b1634ea297a717f2252c9573a8dcc